### ISSUE TITLE
Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by LawrenceAntony** [jthuraisamy/openxml#3]
Hi Jackson,
I tried this sdk with some pptx and docx file. Its always throws below error:
Cannot read property 'charCodeAt' of undefined

while initiating OpenXmlPackage
var doc = new openXml.OpenXmlPackage(bufBlankDoc2);

Could you please help me to resolve this issue

**Comment by Priestch** [comment]
@LawrenceAntony The reason such error happened is the jszip version is not correct.

`var newPart = new openXml.OpenXmlPart(pkg, f2, null, null, zipFile.data);`
should be
`var newPart = new openXml.OpenXmlPart(pkg, f2, null, null, zipFile.asText());`

And I also fix another error in my custom fork [openxml](https://github.com/Priestch/openxml)

**Comment by jthuraisamy** [comment]
@Priestch thank you for the fixes; I merged them back into this repository.
